// src/lib/components/Header.svelte
<script lang="ts"></script>

<header
	class="bg-base-100/90 border-base-200 fixed top-0 left-0 z-[9999] w-full border-b shadow-sm"
>
	<div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
		<!-- Branding -->
		<a href="/" class="flex items-center gap-3">
			<span class="text-base-content hidden text-base font-semibold tracking-wide sm:inline">
				Rieger Systems
			</span>
		</a>
	</div>
</header>

// components/layout/Header.vue
<template>
  <header class="bg-surface-0 dark:bg-surface-900 shadow-md">
    <div
      class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center h-16"
    >
      <!-- Logo / Firmenname -->
      <NuxtLink to="/" class="text-primary-500 font-bold text-2xl">
        Rieger Systems
      </NuxtLink>

      <!-- Navigation -->
      <nav class="space-x-8 hidden md:flex">
        <NuxtLink to="/" class="text-p-text-color hover:text-primary-500"
          >Start</NuxtLink
        >
        <NuxtLink to="/about" class="text-p-text-color hover:text-primary-500"
          >Über uns</NuxtLink
        >
        <NuxtLink
          to="/produkte"
          class="text-p-text-color hover:text-primary-500"
          >Produkte</NuxtLink
        >
        <NuxtLink to="/kontakt" class="text-p-text-color hover:text-primary-500"
          >Kontakt</NuxtLink
        >
      </nav>
    </div>
  </header>
</template>

<script setup lang="ts"></script>
