// components/navigation/Footer.vue
<template>
  <footer
    class="bg-base-100 border-t border-base-300 text-sm text-base-content/80"
  >
    <div class="max-w-screen-xl mx-auto px-6 py-12 grid gap-10 md:grid-cols-4">
      <!-- Branding / Mission -->
      <div class="flex flex-col gap-4">
        <div class="flex items-center gap-3">
          <img
            src="/short-logo.jpg"
            alt="Rieger Systems Logo"
            class="w-8 h-8 rounded-sm"
          />
          <span class="text-lg font-semibold text-primary">Rieger Systems</span>
        </div>
        <p class="text-sm text-base-content/60 leading-relaxed">
          Wir entwickeln Technologie, die Menschen stärkt - nicht überfordert.
          Klar. Sicher. Mit Verantwortung.
        </p>
      </div>

      <!-- Produkt -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Produkt</h3>
        <ul class="space-y-2">
          <li>
            <NuxtLink to="/products" class="hover:text-primary"
              >Leistungen</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/projects" class="hover:text-primary"
              >Projekte</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/contact" class="hover:text-primary"
              >Kontakt</NuxtLink
            >
          </li>
        </ul>
      </div>

      <!-- Info -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Information</h3>
        <ul class="space-y-2">
          <li><NuxtLink to="/faq" class="hover:text-primary">FAQ</NuxtLink></li>
          <li>
            <NuxtLink to="/about" class="hover:text-primary">Über uns</NuxtLink>
          </li>
          <li>
            <NuxtLink to="/ethics" class="hover:text-primary"
              >Ethik & Werte</NuxtLink
            >
          </li>
        </ul>
      </div>

      <!-- Rechtliches -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Rechtliches</h3>
        <ul class="space-y-2">
          <li>
            <NuxtLink to="/imprint" class="hover:text-primary"
              >Impressum</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/privacy" class="hover:text-primary"
              >Datenschutz</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/terms" class="hover:text-primary">AGB</NuxtLink>
          </li>
        </ul>
      </div>
    </div>

    <!-- Footer-Final -->
    <div
      class="border-t border-base-300 mt-10 pt-6 px-6 pb-10 text-xs text-center text-base-content/50 space-y-2"
    >
      <p>
        © {{ new Date().getFullYear() }} Rieger Systems · Alle Rechte
        vorbehalten
      </p>
      <p>
        Wir respektieren deine Privatsphäre. Statistische Auswertungen erfolgen
        anonym und ohne Cookies.
      </p>
    </div>
  </footer>
</template>

// src/components/sections/Footer.svelte
<script lang="ts">
	import { Mail, Globe, ShieldCheck } from 'lucide-svelte';
	import { locale } from '$lib/stores/locale';
	import { de } from '$lib/i18n/de';
	import { en } from '$lib/i18n/en';

	$: t = $locale === 'en' ? en : de;
</script>

<div class="bg-base-200 border-base-300 border-t">
	<footer
		class="footer sm:footer-horizontal text-base-content container mx-auto max-w-screen-xl p-10"
	>
		<!-- Logo & Statement -->
		<aside>
			<img src="/short-logo.jpg" alt="Rieger Logo" class="mb-2 w-36 rounded-2xl" />
			<p>
				<strong class="text-lg">{t.footer.company.title}</strong><br />
				{t.footer.company.desc}<br />
				{t.footer.company.tagline}
			</p>
		</aside>

		<!-- Werte -->
		<nav>
			<h6 class="footer-title">{t.footer.values.title}</h6>
			{#each t.footer.values.items as item}
				<p>{item}</p>
			{/each}
		</nav>

		<!-- Kontakt -->
		<nav>
			<h6 class="footer-title">{t.footer.contact.title}</h6>
			<a href="mailto:{t.footer.contact.email}" class="flex items-center gap-1">
				<Mail class="h-4 w-4" />
				{t.footer.contact.email}
			</a>
			<p class="flex items-center gap-1">
				<Globe class="h-4 w-4" />
				{t.footer.contact.location}
			</p>
			<p class="flex items-center gap-1">
				<ShieldCheck class="h-4 w-4" />
				{t.footer.contact.dsgvo}
			</p>
		</nav>

		<!-- Rechtliches -->
		<nav>
			<h6 class="footer-title">{t.footer.legal.title}</h6>
			<a class="link link-hover" href="/imprint">{t.footer.legal.imprint}</a>
			<a class="link link-hover" href="/privacy-policy">{t.footer.legal.privacy}</a>
		</nav>
	</footer>

	<div
		class="text-base-content/50 mt-4 mb-6 flex flex-col items-center justify-center gap-1 text-center text-xs sm:flex-row"
	>
		<span>© {new Date().getFullYear()} Rieger Systems e.U. · {t.footer.copyright}</span>
		<span class="sm:ml-2">🍪 {t.footer.cookies}</span>
	</div>
</div>
