// src/lib/components/Footer.svelte
<script lang="ts">
	import { Mail, Globe, ShieldCheck } from 'lucide-svelte';
</script>

<div class="bg-base-200 border-base-300 border-t">
	<footer
		class="footer sm:footer-horizontal text-base-content container mx-auto max-w-screen-xl p-10"
	>
		<!-- Logo & Statement -->
		<aside>
			<img src="/short-logo.jpg" alt="Rieger Logo" class="mb-2 w-36 rounded-2xl" />
			<p>
				<strong class="text-lg">Rieger Systems GmbH</strong><br />
				Technologie, die Verantwortung trägt.<br />
				Made in Europe.
			</p>
		</aside>

		<!-- Werte -->
		<nav>
			<h6 class="footer-title">Wofür wir stehen</h6>
			<p>Datenschutz & Transparenz</p>
			<p>Menschzentrierte Systeme</p>
			<p>Europäische Verantwortung</p>
			<p>Technologische Exzellenz</p>
		</nav>

		<!-- Kontakt -->
		<nav>
			<h6 class="footer-title">Kontakt</h6>
			<a href="mailto:kontakt@rieger-systems.eu" class="flex items-center gap-1">
				<Mail class="h-4 w-4" /> kontakt@rieger-systems.eu
			</a>
			<p class="flex items-center gap-1">
				<Globe class="h-4 w-4" /> Europa-basiert
			</p>
			<p class="flex items-center gap-1">
				<ShieldCheck class="h-4 w-4" /> DSGVO-konform
			</p>
		</nav>

		<!-- Rechtliches -->
		<nav>
			<h6 class="footer-title">Rechtliches</h6>
			<a class="link link-hover" href="/imprint">Impressum</a>
			<a class="link link-hover" href="/privacy-policy">Datenschutzerklärung</a>
		</nav>
	</footer>

	<div class="text-base-content/50 mt-4 mb-6 text-center text-xs">
		© {new Date().getFullYear()} Rieger Systems GmbH · Alle Rechte vorbehalten.
	</div>
</div>

// components/navigation/Footer.vue
<template>
  <footer
    class="bg-base-100 border-t border-base-300 text-sm text-base-content/80"
  >
    <div class="max-w-screen-xl mx-auto px-6 py-12 grid gap-10 md:grid-cols-4">
      <!-- Branding / Mission -->
      <div class="flex flex-col gap-4">
        <div class="flex items-center gap-3">
          <img
            src="/short-logo.jpg"
            alt="Rieger Systems Logo"
            class="w-8 h-8 rounded-sm"
          />
          <span class="text-lg font-semibold text-primary">Rieger Systems</span>
        </div>
        <p class="text-sm text-base-content/60 leading-relaxed">
          Wir entwickeln Technologie, die Menschen stärkt - nicht überfordert.
          Klar. Sicher. Mit Verantwortung.
        </p>
      </div>

      <!-- Produkt -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Produkt</h3>
        <ul class="space-y-2">
          <li>
            <NuxtLink to="/products" class="hover:text-primary"
              >Leistungen</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/projects" class="hover:text-primary"
              >Projekte</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/contact" class="hover:text-primary"
              >Kontakt</NuxtLink
            >
          </li>
        </ul>
      </div>

      <!-- Info -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Information</h3>
        <ul class="space-y-2">
          <li><NuxtLink to="/faq" class="hover:text-primary">FAQ</NuxtLink></li>
          <li>
            <NuxtLink to="/about" class="hover:text-primary">Über uns</NuxtLink>
          </li>
          <li>
            <NuxtLink to="/ethics" class="hover:text-primary"
              >Ethik & Werte</NuxtLink
            >
          </li>
        </ul>
      </div>

      <!-- Rechtliches -->
      <div>
        <h3 class="text-base font-semibold text-primary mb-4">Rechtliches</h3>
        <ul class="space-y-2">
          <li>
            <NuxtLink to="/imprint" class="hover:text-primary"
              >Impressum</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/privacy" class="hover:text-primary"
              >Datenschutz</NuxtLink
            >
          </li>
          <li>
            <NuxtLink to="/terms" class="hover:text-primary">AGB</NuxtLink>
          </li>
        </ul>
      </div>
    </div>

    <!-- Footer-Final -->
    <div
      class="border-t border-base-300 mt-10 pt-6 px-6 pb-10 text-xs text-center text-base-content/50 space-y-2"
    >
      <p>
        © {{ new Date().getFullYear() }} Rieger Systems · Alle Rechte
        vorbehalten
      </p>
      <p>
        Wir respektieren deine Privatsphäre. Statistische Auswertungen erfolgen
        anonym und ohne Cookies.
      </p>
    </div>
  </footer>
</template>
